---
- name: Install everything needed on host machine (terraform, kubectl, awscli and helm)
  hosts: localhost
  become: true
  
  tasks:
    - name: Install kubectl v1.22
      shell: |
        curl -LO https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl && \
        chmod +x ./kubectl && \
        sudo mv ./kubectl /usr/local/bin/kubectl


    - name: Install awscli
      apt:
        name: awscli
        state: present

    - name: Install helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash


    - name: Install eksctl
      shell: |
        sudo apt-get update && \
        sudo apt-get install -y apt-transport-https && \
        sudo curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | sudo tar xz -C /usr/local/bin

    - name: Install terraform v1.3.7
      shell: |
        wget https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_amd64.zip && \
        unzip terraform_1.3.7_linux_amd64.zip && \
        sudo mv terraform /usr/local/bin/ && \
        rm terraform_1.3.7_linux_amd64.zip
